module Locale
  class Texts
  def portuguese
    {:prompt_extension => "pt-br",
    :currency => "reais ",
    :number => "número ",
    :categories_intro => "Para a categoria ",
    :product_item => "Número do produto ",
    :price => "preço ",
    :amount => "quantidade ",
    :units => "unidades ",
    :user_expectation => "O usuário espera que o produto e pagar quando receber um projeto de lei ",
    :to_pay => "Para pagar com VISA, Mastercard ou American Express Pressão 1 ",
    :intro => "Bom dia, boa tarde e boa noite Esta é uma ordem real, feita pelo usuário ",
    :intro_after_user => "Fazendo uso do novo pedido de compra e venda de inteligente, chamado smartbands. ",
    :address => "O pedido foi feito a partir do seguinte endereço, ",
    :product_iteration => "Os produtos encomendados são os seguintes. ",
    :choose_one => "Escolha uma das opções a seguir. ",
    :push => "Press ",
    :for => "a ",
    :repeat => "Repeat Ordem ",
    :confirmation => "Confirme se o pedido será enviado ",
    :cancelation => "Cancel Order ",
    :balance => "Load Balance em seus smartbands conta ",
    :ban => "deixam de receber ordens smartbands ",
    :exit => "Exit ",
    :confirmed => "Em boa hora, basta confirmar o pedido do cliente foi notificado e esperamos que a sua encomenda chegue a tempo Paa recomendo baixar nossos custos de aplicação reduzir telefonemas de www.smartbands.com Obrigado por usar smartbands. ",
    :canceled => "Você só cancelou a ordem O cliente será notificado Obrigado por usar smartbands. ",
    :sorry => "Nós lamentamos a sua desicion de não receber mais ordens chamado real e próximo ao seu ponto de venda a partir das smartbands aplicação Se você quiser voltar a receber ordens para fazê-los pedir-nos saber por visitar nosso site, www.smartbands.com. Muchas gracias, smartbands equipe. ",
    :thankyou  => "Obrigado por usar smartbands. ",
    :card_intro => "Carregar saldo da conta smartbands deve digitar o tipo, número, data de validade, código de seu cartão de crédito segurança e quantidade de carga Abaixo inserir dados usando o teclado numérico do telefone. seguro. ",
    :card_type_prompt => "Digite o tipo de cartão de crédito ",
    :card_type => "Tipo de cartão ",
    :card_say_type => "Say Visa, MasterCard ou American Express. ",
    :card_input_number_prompt => "Digite o número do seu cartão de crédito ",
    :card_number => "Número do cartão ",
    :card_number_input_fifteen => "Digite os 15 dígitos do seu cartão de crédito. ",
    :card_number_input_sixteen => "Digite os 16 dígitos do seu cartão de crédito. ",
    :card_number_info_amex => "Os números de cartões American Express tem 15 dígitos. ",
    :card_number_info_visa_master => "Número de cartão de crédito MasterCard e Visa têm 16 dígitos. ",
    :card_input_expiration => "Digite a data de vencimento do seu cartão de crédito. ",
    :card_expiration => "Data de Expiração ",
    :card_expiration_input_ie => "Digite a data de validade, por exemplo, um ou dois. ",
    :card_i_have => "eu tenho ",
    :card_expires_when => "expira ",
    :card_ask_if_correct => "Isto é informação correta "
}
    end
end
end