module Locale
class Texts
  def italian
   {
    :prompt_extension => "it-it",
    :currency => "euros ",
    :number => "numero ",
    :categories_intro => "Per la categoria ",
    :product_item => "numero di prodotto ",
    :price => "prezzo ",
    :amount => "quantità ",
    :units => "unità ",
    :user_expectation => "L'utente si aspetta che il prodotto e pagare quando si riceve una fattura ",
    :to_pay => "Per pagare con VISA, Mastercard o American Express pressione 1 ",
    :intro => "Buongiorno, buon pomeriggio e buona notte. Questo è un ordine reale, fatta dall'utente. ",
    :intro_after_user => " Facendo uso della nuova domanda di acquisto e vendita di intelligenti, detti smartbands. ",
    :address => "La richiesta è stata fatta al seguente indirizzo, ",
    :product_iteration => "Prodotti ordinati sono i seguenti. ",
    :choose_one => "Scegliere una delle seguenti opzioni. ",
    :push => "premere ",
    :for => "a ",
    :repeat => "Ripetere l'ordine ",
    :confirmation => "Verificare che l'ordine verrà inviato ",
    :cancelation => "Annullare l'ordine ",
    :balance => "Caricare saldo del tuo conto smartbands ",
    :ban => "Non più ricevere ordini smartbands ",
    :exit => "lasciare ",
    :confirmed => "In tempo utile, è sufficiente confermare l'ordine. Il cliente è stato notificato e aspettatevi che il vostro ordine arriva in tempo. Ti consigliamo di scaricare la nostra applicazione paa ridurre i costi di telefonate da www.smartbands.com. Grazie per aver scelto smartbands voi. ",
    :canceled => "Usted acaba de cancelar el pedido. El cliente sera notificado. Gracias por utilizar smartbands. ",
    :sorry => "Ci scusiamo per il tuo desicion di non ricevere più ordini chiama reale e vicino al suo punto vendita dalle smartbands applicativi. Se desiderate richiedere ordini prendono nuovamente fatto conoscere visitando il nostro sito internet, www.smartbands.com. Molte grazie, smartbands team. ",
    :thankyou  => "Grazie per aver scelto smartbands voi. ",
    :card_intro => "smartbands Caricamento saldo del conto deve indicare il tipo, numero, data di scadenza, codice di sicurezza della carta di credito e la quantità di carico seguito immettere i dati usando il telefono cellulare tastierino numerico di. in modo sicuro, ",
    :card_type_prompt => "Inserisci il tipo di carta di credito ",
    :card_type => "Tipo di carta ",
    :card_say_type => "Dimmi Visa, MasterCard o American Express. ",
    :card_input_number_prompt => "Inserisci il numero della tua carta di credito ",
    :card_number => "Numero carta ",
    :card_number_input_fifteen => " Inserire le 15 cifre della carta di credito. ",
    :card_number_input_sixteen => "Inserire le 16 cifre della carta di credito. ",
    :card_number_info_amex => "I numeri di carta di credito American Express hanno 15 cifre. ",
    :card_number_info_visa_master => "Numeros de tarjeta de credito MasterCard y Visa tienen 16 digitos. ",
    :card_input_expiration => "Inserire la data di scadenza della tua carta di credito ",
    :card_expiration => "Data di Scadenza ",
    :card_expiration_input_ie => "Inserire la data di scadenza, per esempio, uno o due. ",
    :card_i_have => "Io sono ",
    :card_expires_when => "scade ",
    :card_ask_if_correct => "È questo il informazioni corrette "
}
  end
  end
end