module Locale
class Texts
  def spanish
  {:prompt_extension => "es-mx",
  :currency => "pesos argentinos ",
  :number => "numero ",
  :categories_intro => "Para la categoria ",
  :product_item => "Producto numero ",
  :price => "precio ",
  :amount => "cantidad ",
  :units => "unidades ",
  :user_expectation => "El usuario espera el producto y pagara cuando lo reciba con un billete de ",
  :to_pay => "Para realizar un pago con VISA, Mastercard o American Express presion 1 ",
  :intro => "Buenos dias, buenas tardes, y buenas noches. Este es un pedido real, realizado por, el usuario. ",
  :intro_after_user => "Haciendo uso del nuevo aplicativo de compra y venta de artículos inteligente, llamado smartbands. ",
  :address => "El pedido fue realizado desde la siguiente direccion, ",
  :product_iteration => "Los productos ordenados son los siguientes. ",
  :choose_one => "Elija una de las siguientes opciones. ",
  :push => "Presione ",
  :for => "para ",
  :repeat => "Repetir el pedido ",
  :confirmation => "Confirmar que el pedido sera enviado ",
  :cancelation => "Cancelar el pedido ",
  :balance => "Cargar saldo en su cuenta smartbands ",
  :ban => "No volver a recibir pedidos de smartbands ",
  :exit => "Salir ",
  :confirmed => "En hora buena, usted acaba de confirmar el pedido. El cliente fue notificado y espera su pedido llegue a tiempo. Recomendamos descargue nuestro aplicativo paa reducir costos en llamados telefonicos, desde www.smartbands.com. Gracias por utilizar smartbands. ",
  :canceled => "Usted acaba de cancelar el pedido. El cliente sera notificado. Gracias por utilizar smartbands. ",
  :sorry => "Lamentamos su desicion de no recibir mas llamados de pedidos reales y cercanos a su punto de venta desde la aplicacion smartbands. En caso de desear volver a recibir pedidos solicitamos nos los haga saber, visitando nuestro sitio web, www.smartbands.com . Muchas Gracias, el equipo de smartbands. ",
  :thankyou  => "Gracias por utilizar smartbands. ",
  :card_intro => "Para cargar saldo en su cuenta smartbands debera ingresar el tipo, numero, fecha de expiracion, codigo de seguridad, de su tarjeta de credito y monto a cargar. A continuacion ingrese los datos utilizando el teclado numerico su telefono, de manera segura. ",
  :card_type_prompt => "Ingrese el tipo de su tarjeta de credito ",
  :card_type => "Tipo de tarjeta ",
  :card_say_type => "Diga Visa, MasterCard, o American Express. ",
  :card_input_number_prompt => "Ingrese el numero de su tarjeta de credito ",
  :card_number => "Numero de tarjeta ",
  :card_number_input_fifteen => "Ingrese los 15 digitos de su tarjeta de credito. ",
  :card_number_input_sixteen => "Ingrese los 16 digitos de su tarjeta de credito. ",
  :card_number_info_amex => "Los numeros de tarjeta American Express tienen 15 digitos. ",
  :card_number_info_visa_master => "Numeros de tarjeta de credito MasterCard y Visa tienen 16 digitos. ",
  :card_input_expiration => "Ingrese la fecha de expiracion de su tarjeta de credito. ",
  :card_expiration => "Fecha de expiracion ",
  :card_expiration_input_ie => "Ingrese la fecha de expiracion, por ejemplo, uno o dos. ",
  :card_i_have => "Yo tengo ",
  :card_expires_when => "expira el ",
  :card_ask_if_correct => "Es esta informacion correcta "
}
  end
end
end